### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by jichon** [untangled-web/untangled-websockets#1]
When network client processing the error returned from the server, it fails with the following error: 

No protocol method IDeref.-deref defined for type function: function (status,error){
return null;
}

It seems like global-error-callback is not wrapped with `atom` and callback tries to deref the passed in function directly causing this issue.

**Comment by mahinshaw** [comment]
Thanks for letting me know about this.  Fix is up.  A new release will show up on clojars today.

**Comment by jichon** [comment]
No problem. Well I have to thank your team for providing the community with fantastic framework to accomplish the work easily, efficiently and not leaving an aweful taste at the end of the day. Loving it. Thank you for that quick fix.

**Comment by mahinshaw** [comment]
Glad you are liking it! It's good to have feedback, and see other people using it.
